language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

php: [7.1]

env:
  global:
    # Node version needed for zombie 3.0.
    - NODE_VERSION='11.10.1'
    # Force binding to IPv4 as Zombie and PHP seem to have a different resolution for localhost on Travis.
    - MINK_HOST=127.0.0.1:8002

before_install:
  - wget https://nodejs.org/dist/v${NODE_VERSION}/node-v${NODE_VERSION}-linux-x64.tar.gz && tar xfz node-v${NODE_VERSION}-linux-x64.tar.gz && export PATH="`pwd`/node-v${NODE_VERSION}-linux-x64/bin:$PATH"

  - if [[ "${PHPUNIT_VERSION}" != "" ]]; then composer require --dev phpunit/phpunit:${PHPUNIT_VERSION}; fi

  - node --version
  - npm --version

install:
  - composer install
  - npm install zombie

before_script:
  # Start a webserver for web fixtures.
  - vendor/bin/mink-test-server &

  # Set the PHPUnit executable to the local or global one
  - if [[ "${PHPUNIT_VERSION}" != "" ]]; then PHPUNIT_CMD=vendor/bin/phpunit; else PHPUNIT_CMD=phpunit; fi

script:
  - ${PHPUNIT_CMD} -v --coverage-clover=coverage.clover
